name: fsrs
description: A Dart package for FSRS, which implements the Free Spaced Repetition Scheduler algorithm. This package assists developers in incorporating FSRS into their flashcard applications.

version: 1.1.0
repository: https://github.com/open-spaced-repetition/dart-fsrs

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
